rails_projects/todo/config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'

resources :listings

end

rails_projects/todo/app/models/listing.rb
class Listing < ActiveRecord::Base
  
  validates_presence_of :description
  
end

rails_projects/todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_projects/todo/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def index
    @listings = Listing.all
  end
  
  def new
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to listings_path
    
    else
      render 'new'
    end
  end
  
  def edit
    @listing = Listing.find(params[:id])
  end
  
  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to listings_path
    else
      render 'edit'
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    
    redirect_to listings_path
  end
    
  private
    def listing_params
      params.require(:listing).permit(:description)
    end
  
  
  
end

rails_projects/todo/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_projects/todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails_projects/todo/app/views/listings/_form.html.erb
<% if obj.errors.any? %>
  <h2>There was an error in your submission.</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @listing do |f| %>
  <p>
    <%=f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.submit(obj.new_record? ?  "Create New To Do" : "Edit To Do") %>
  </p>
<% end %>

rails_projects/todo/app/views/listings/edit.html.erb
<h1>Edit Your To Do</h1>

<%= render 'form', obj: @listing %>

rails_projects/todo/app/views/listings/index.html.erb
<h1>To Do's</h1>

<% @listings.each do |listing| %>
  <ul>
    <li><%= link_to listing.description, listing_path(listing) %></li>
    <%= link_to "edit todo", edit_listing_path(listing) %>
    <%= link_to "[Delete To Do]", listing, method: :delete, data: { confirm: "Are You Sure?" } %>
  </ul>


<% end %>

<%= link_to "Create A New 'To do'", new_listing_path %>

rails_projects/todo/app/views/listings/new.html.erb
<h1>Add A New To Do</h1>

<%= render 'form', obj: @listing %>

rails_projects/todo/app/views/listings/show.html.erb
<h1>View Your To Do</h1>
<p>
  <%= @listing.description %>
</p>
<p>
  <%= link_to "Edit This To Do", edit_listing_path(@listing) %>
</p>
<p>
  <%= link_to "Back To To Do's Listing", listings_path %>
</p>